# Generated by Django 4.1.7 on 2023-04-06 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
